# Generated by Django 5.1.5 on 2025-01-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_logo',
            field=models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Лого проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='tehnology_project',
            field=models.TextField(default='Технологии не указаны', verbose_name='Технологии проекта'),
        ),
    ]
